environments:
  DEV:
    cmdb:
      appid: APP000020011845
    btp:
      authHost: jnj-im-dev-na.authentication.us10.hana.ondemand.com
      cpiHost: jnj-im-dev-na.it-cpi019-rt.cfapps.us10-002.hana.ondemand.com
      apiHost: us10apiportal.cfapps.us10.hana.ondemand.com
      cpiCredentialsId: CPI_OAUTH_CRED_JNJ_IM_DEV_NA
      apiCredentialsId: API_OAUTH_CRED_JNJ_IM_DEV_NA
      environment: dev
    artifactory:
      url: https://artifactrepo.jnj.com/artifactory
      artifactPath: jeas-ivy/cpilint-1.0.5
      cpilintBuildVersion: 1.0.5
      dockerImage: jnj.artifactrepo.jnj.com/jpm/openjdk:17-jdk-slim
